<div class="right">
    <?php echo $this->ajax('back', 'forum/index/index', 2); ?>
</div>
<div class="forum">
    <div id="forum-page">
        <?php echo $this->paginationControl($this->data); ?>
    </div>
    <br />
    <?php $identity = Zend_Auth::getInstance()->getIdentity()?>
    <?php if (count($this->data)):?>
    <table class="datatable">
        <?php foreach ($this->data as $key => $data): ?>
            <?php
                $highlight = null;
                if ($data->role != 'student') {
                    $highlight = "highlight";
                }
            ?>
            <tr class="space <?php echo $highlight?>"><td colspan="3">&nbsp;</td></tr>
            <tr class="info <?php echo $highlight?>">
                <td class="image" rowspan="2" width="60" valign="top" align="center">
                    <img alt="<?php echo $data->name ?>" src="upload/<?php echo $this->thumbnail($data->image, 'small') ?>" /><br />
                </td>
                <td>
                    <span class="name">
                        <?php echo $data->name;?>
                        <?php if ($data->role != 'student'):?>
                            (<?php echo $this->translate($data->role)?>)
                        <?php endif;?>
                    </span><br />
                </td>
                <td nowrap="nowrap" align="right">
                    <span class="name"><?php echo $this->date($data->created, true)?></span>
                </td>
            </tr>
            <tr class="description <?php echo $highlight?>">
                <td colspan="2">
                    <?php echo nl2br($data->description);?>
                </td>
            </tr>
        <?php endforeach;?>
    </table>
    <?php else:?>
        <p><?php echo $this->translate('there are no records')?></p>
    <?php endif;?>
    <div id="forum-page">
        <?php echo $this->paginationControl($this->data) ?>
    </div>
</div>
<script type="text/javascript">
    $('#forum-page a').click(function(){
        $(this).parents('.content').load(this.href);
        return false;
    });
    
    $('input[type=button], input[type=submit]').button();
</script>