<div class="left">
    <form id="formFindForum" action="#">
        <input type="text" name="query" style="width: 16em" />
        <input class="btn" type="submit" value="ok" /> &nbsp;&nbsp;&nbsp;
    </form>
</div>
<?php if($this->isAllowed('form')): ?>	
	<div class="aright"><?php echo $this->ajax("new", 'forum/index/form/', 3); ?></div>
<?php endif; ?>	
<?php if (count($this->data)):?>
    <br />
    <table class="zebra-striped">
        <tr>
            <th><?php echo $this->translate('Name')?></th>
            <th><?php echo $this->translate('Comments')?></th>
            <th><?php echo $this->translate('Status')?></th>
            <th></th>
        </tr>
        <?php foreach ($this->data as $data): ?>
            <?php $newMessages = Forum_Model_Access::verify($data->id, Zend_Auth::getInstance()->getIdentity()->id);?>
            <tr>
                <td><?php echo $this->ajax($data->title, 'forum/reply/index/id/' . $data->id);?></td>
                <td><?php echo Forum_Model_Reply::count($data->id)?></td>
                <td>
                    <?php if ($data->status == 'active'):?>
                        <?php if ($newMessages):?>
                            <?php echo $newMessages?> <?php echo $this->translate(array('new comment', 'new comments', $newMessages), $this->locale)?>
                        <?php else:?>
                            <?php echo $this->translate('There are no new comments')?>
                        <?php endif;?>
                    <?php else:?>
                        <?php echo $this->translate('inactive')?>
                    <?php endif;?>
                </td>
                <td width="40">
                    <?php if ($this->isAllowed('form')): ?>
                        <?php echo $this->ajax("edit", 'forum/index/form/id/'. $data->id, 2); ?>
                    <?php endif;?>
                </td>
            </tr>
        <?php endforeach;?>
    </table>
    <div id="forum-page">
        <?php echo $this->paginationControl($this->data) ?>
    </div>
<?php else:?>
    <p><?php echo $this->translate( "there are no records" );?></p>
<?php endif;?>
<script type="text/javascript">
    $('#forum-page a').click(function(){
        $(this).parents('.content').load(this.href);
        return false;
    });

    $("#formFindForum").submit(function() {
		$(this).parents('.content').load('forum/reply/find/?' + $(this).serialize());
        return false;
	});

    
</script>